# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1604_TAR = struct(
    revision = "1563988761",
    sha256 = "51b4187cf5bedc1dd1ce3077446be11d884fa27d3c8fc351495e6d2f2211e300",
)

DEBS_TARBALL = struct(
    revision = "1563988761",
    sha256 = "f022683d76102b75f7304e2c7b60e9d3a429abf3e0172320fc8869a63b8a6345",
)
