# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU2004_TAR = struct(
    revision = "1670578323",
    sha256 = "b9db3e1c80bed7d2364f886b9d1b7cb9efcc762d54f11fc1364fca1b36ef2b3a",
)

DEBS_TARBALL = struct(
    revision = "1672943501",
    sha256 = "a77d7ababbee99e2cda42ae314cb37645f6c42665513e9ca8163993525ec19f0",
)

RULES_DOCKER = struct(
    commit = "master",
    sha256 = "31661d44f3992b8cde040ed562b85732572c0f5109e4f9521ccbe6b65b13a85d",
)
