# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU2004_TAR = struct(
    revision = "1651224679",
    sha256 = "62028c31d4c0627e9cbf40b4a0580a1d1b5068452ba74969d7670712a60d93dd",
)

DEBS_TARBALL = struct(
    revision = "1652239885",
    sha256 = "a89353a0798525ce210eb6ae8bab4116863bb5182a98b1573ddcffb531587964",
)

RULES_DOCKER = struct(
    commit = "6ea707babdcd54514e0884278ac624fb8bda19c1",
    sha256 = "9e02383f6b2d45fe05398fd342fbfdc51862bed0b355c139e2e18c5c972d794d",
)
