# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU2004_TAR = struct(
    revision = "1681291897",
    sha256 = "7a802c94425af594acd073d5c20b2b6af072052cf9031c584bf1b36f79459836",
)

DEBS_TARBALL = struct(
    revision = "1686043882",
    sha256 = "276ee1d4d0c67bf8727e8ec85a0f474a0e2cc72ccbb262b9f88188a3a430438b",
)

RULES_DOCKER = struct(
    commit = "master",
    sha256 = "ee0ae721320e163e7693a549497fa98842bd57d80f52aeec9696e3c94179684f",
)
