# Copyright 2021 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

steps:
# Step: build the rootfs
  - name: "ubuntu"
    env:
      - 'DISTRO_NAME=${_DISTRO_NAME}'
    script: |
      #!/usr/bin/env bash
      apt-get update
      apt-get -y install debootstrap
      debootstrap --variant=minbase --include=curl,bzip2,ca-certificates "${DISTRO_NAME}" "${DISTRO_NAME}"
      tar -C "${DISTRO_NAME}" -czf rootfs.tar.gz .
    id: "rootfs"

# Step: build the image
  - name: "gcr.io/cloud-builders/docker"
    args: ["import", "rootfs.tar.gz", "base-image-temp"]
    id: "container-build"

# Step: build the image
  - name: "gcr.io/cloud-builders/docker"
    dir: ubuntu1804
    args: ["build", "-t", "gcr.io/${_IMG_DEST}", "."]
    id: "upgrade-dist"

# Step: tags
  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/${_IMG_DEST}", "us.gcr.io/${_IMG_DEST}"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/${_IMG_DEST}", "eu.gcr.io/${_IMG_DEST}"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/${_IMG_DEST}", "asia.gcr.io/${_IMG_DEST}"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["tag", "gcr.io/${_IMG_DEST}", "gcr.io/${_IMG_BACKUP_DEST}"]

substitutions:
    # Default values for substitution variables.
    # These variables are altered in the cloudbuild trigger definition
    #_IMG_DEST: gcp-runtimes/ubuntu_20_0_4:latest-new
    #_IMG_BACKUP_DEST: asci-toolchain-backup/ubuntu2004:latest-new
    _DISTRO_NAME: bionic
    _IMG_DEST: gcp-runtimes/ubuntu_18_0_4:latest-new
    _IMG_BACKUP_DEST: asci-toolchain-backup/ubuntu1804:latest-new

# Push the new image and its backup.
# Push by using the `images` field here so they will show up in the build results
# or the GCB Build information page.
# https://cloud.google.com/cloud-build/docs/configuring-builds/store-images-artifacts
images:
  - "gcr.io/${_IMG_DEST}"
  - "us.gcr.io/${_IMG_DEST}"
  - "eu.gcr.io/${_IMG_DEST}"
  - "asia.gcr.io/${_IMG_DEST}"
  - "gcr.io/${_IMG_BACKUP_DEST}"
