# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1804_TAR = struct(
    revision = "1668097956",
    sha256 = "8ff78095f7172faaad0ef59df4f5ccae667d8824a37fa7a3f44960119595c598",
)

DEBS_TARBALL = struct(
    revision = "1670459484",
    sha256 = "34976a2870cc392148af316054115436ad6de71641a261b5a14bd2834943a4e7",
)

RULES_DOCKER = struct(
    commit = "master",
    sha256 = "2070e3f1cb42c5711cb4194ceda15d1412ac7c9b9b4fc3acf67aee5022a3c52f",
)
