# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1804_TAR = struct(
    revision = "1590503490",
    sha256 = "72f5a5b324c909c11385d338d2b36e8ec034f9247227aef5bb0791a85863c91b",
)

DEBS_TARBALL = struct(
    revision = "1591025611",
    sha256 = "7d0118cac93a0c6ecd4b413ee295055a1422712c661e403d62c22feb5c60e3e9",
)

RULES_DOCKER = struct(
    commit = "f1557ebc5381e2a662314e21585aa8080e9508be",
    sha256 = "ffd6ee22fceb7db4d6e6f75bf69ecf439da7500ec2969fc5d371d165ceb22e3f",
)
