# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1804_TAR = struct(
    revision = "1593531368",
    sha256 = "32621f77b04b7811bbb58497aa71e3f50dbcf1539a91ce1737170ddd1567a085",
)

DEBS_TARBALL = struct(
    revision = "1593005598",
    sha256 = "531663d36ada8e5bffe7cada8cf0e2ef6685ef96d273c5f4add4a4fb1769585c",
)

RULES_DOCKER = struct(
    commit = "f1557ebc5381e2a662314e21585aa8080e9508be",
    sha256 = "ffd6ee22fceb7db4d6e6f75bf69ecf439da7500ec2969fc5d371d165ceb22e3f",
)
