package(default_visibility = ["//visibility:public"])

py_binary(
    name = "config_stripper",
    srcs = ["config_stripper.py"],
)

exports_files(["commit.sh.tpl"])

exports_files(["extract.sh.tpl"])
