package(default_visibility = ["//visibility:public"])

py_binary(
    name = "config_stripper",
    srcs = ["config_stripper.py"],
)

py_binary(
    name = "md5",
    srcs = ["md5.py"],
)

exports_files(["commit.sh.tpl"])
exports_files(["extract.sh.tpl"])
