# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CENTOS8_TAR = struct(
    revision = "1641825070",
    sha256 = "85e0e93884ad8fc2e132d97050006a3448c506cd86bb2d9475e7316ea5e7e30e",
)

RULES_DOCKER = struct(
    commit = "86c54e5a3a2a4ae9c0cc39b3af7d94c04ac689ab",
    sha256 = "7863f4fb51e4801b91942ab3cf00a673c53ed555d27a56f4287c2619d13830eb",
)
