# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CENTOS8_TAR = struct(
    revision = "1634934806",
    sha256 = "7e64c0742c0b473f1e1213bac78f1b9f417e0e0ba2b04eede9cd9aa18604bd56",
)

RULES_DOCKER = struct(
    commit = "af2b074cc8f488e0dcec6230c63c2a7c34cf3dff",
    sha256 = "2b72a72532e2ca0c3991b9f4775c191f9ab24780c72a232c32296af40e31b6ee",
)
