# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1604_TAR = struct(
    revision = "1599150737",
    sha256 = "de0b31c36d422d20b8f58df824ae25ac568a1d0f1f80d58a63f279fca9e7cc05",
)

DEBS_TARBALL = struct(
    revision = "1597843912",
    sha256 = "81708fa3aaf167a94ffa791314ea6d45b93111b16fc551f12cf09bb5f0db81a4",
)

RULES_DOCKER = struct(
    commit = "faaa10a72fa9abde070e2a20d6046e9f9b849e9a",
    sha256 = "feb53c560be2f97b7d02b23a1738a3154ba89fe630f09a7a838dcad38731b0b8",
)
