# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

UBUNTU1604_TAR = struct(
    revision = "1619681481",
    sha256 = "1bb1746566c5498cba50369105d52fad4530691b1940e56380a1f6ed741dac1c",
)

DEBS_TARBALL = struct(
    revision = "1620934281",
    sha256 = "7194f8ba2e6fec3ef91267200e63d77f9ef01f65130379cf298c4c61d3bd8461",
)

RULES_DOCKER = struct(
    commit = "881e779b5c5b2fad2eeda7ed1f5cb9cbfc10fcdb",
    sha256 = "631986d6738f2a98f9bf0a07ef3e122f460112afe752e25bc05c993fc8a5a9e7",
)
