# Copyright 2018 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

workspace(name = "ubuntu1604")

load(
    "@bazel_tools//tools/build_defs/repo:http.bzl",
    "http_archive",
    "http_file",
)

http_archive(
    name = "bazel_toolchains",
    sha256 = "7d0c157364ce8dac5282af7c7b9e8d9e2c4ee7a6a30dfdb763e9e40b09a656e9",
    strip_prefix = "bazel-toolchains-e6e7db64dfcfe82f54782a75ee549b0e392ecefc",
    urls = ["https://github.com/bazelbuild/bazel-toolchains/archive/e6e7db64dfcfe82f54782a75ee549b0e392ecefc.tar.gz"],
)

http_archive(
    name = "io_bazel_rules_docker",
    sha256 = "b16afde01b99f8b9a067b98903a5fa1879307f9344ccdbbc4aa796ae657e910f",
    strip_prefix = "rules_docker-4ea9e6708ec5ac29dc18f991921e2c064969159a",
    urls = ["https://github.com/bazelbuild/rules_docker/archive/4ea9e6708ec5ac29dc18f991921e2c064969159a.tar.gz"],
)

http_archive(
    name = "base_images_docker",
    sha256 = "0ed911fde4427f7d3d9f2b32df13c2b4c43c855eaab52df6ab780e59a3e9270b",
    strip_prefix = "base-images-docker-87df46c7f428f8b8d9be8fde2e653ae27bd9c7cd",
    urls = ["https://github.com/GoogleContainerTools/base-images-docker/archive/87df46c7f428f8b8d9be8fde2e653ae27bd9c7cd.tar.gz"],
)

http_archive(
    name = "bazel_skylib",
    # Commit c00ef493869e2966d47508e8625aae723a4a3054 of 2018-12-10
    sha256 = "7363ae6721c1648017e23a200013510c9e71ca69f398d52886ee6af7f26af436",
    strip_prefix = "bazel-skylib-c00ef493869e2966d47508e8625aae723a4a3054",
    urls = ["https://github.com/bazelbuild/bazel-skylib/archive/c00ef493869e2966d47508e8625aae723a4a3054.tar.gz"],
)

# Non-deterministic latest version of ubuntu1604 base tarball. This is used by
# File Update Service to archive each version in our managed GCS bucket, and
# should NOT be used by container release directly.
# Note that this relies on that https://partner-images.canonical.com/core/bionic/current/...
# always hosts the latest version of the tarball, and we intentionally do not include
# sha256 in this http_file target as the file downloaded are not deterministic.
http_file(
    name = "ubuntu1604_tar_latest",
    downloaded_file_path = "ubuntu1604.tar.gz",
    urls = ["https://partner-images.canonical.com/core/xenial/current/ubuntu-xenial-core-cloudimg-amd64-root.tar.gz"],
)

load(
    "@io_bazel_rules_docker//repositories:repositories.bzl",
    container_repositories = "repositories",
)
load("@bazel_toolchains//repositories:repositories.bzl", bazel_toolchains_repos = "repositories")

bazel_toolchains_repos()

load("@bazel_toolchains//repositories:go_repositories.bzl", bazel_toolchains_go_repos = "go_deps")

bazel_toolchains_go_repos()

container_repositories()

load("@io_bazel_rules_docker//repositories:deps.bzl", container_deps = "deps")

container_deps()

load("@io_bazel_rules_docker//repositories:pip_repositories.bzl", "pip_deps")

pip_deps()

load(":deps.bzl", "deps")

deps()
