# Copyright 2019 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     https://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# This file is autogenerated by the dependency update service and should not be modified directly.
# For more details, check the deps_spec.yaml file in the current folder.

CENTOS7_TAR = struct(
    revision = "1628004683",
    sha256 = "0d47c3affca690ed0d206189b860eb926bf60973e2c02a7696ddd5e7ecea80a8",
)

RULES_DOCKER = struct(
    commit = "881e779b5c5b2fad2eeda7ed1f5cb9cbfc10fcdb",
    sha256 = "631986d6738f2a98f9bf0a07ef3e122f460112afe752e25bc05c993fc8a5a9e7",
)
