package(default_visibility = ["//visibility:public"])

load("@runtimes_common//structure_tests:tests.bzl", "structure_test")

structure_test(
    name = "ubuntu_test",
    config = "//tests:ubuntu_test.yaml",
    image = "//reproducible/ubuntu:ubuntu",
)
